import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';

import { Document, Types } from 'mongoose';

import { Schema as MongooseSchema } from 'mongoose';

export type ReportDocument = Report & Document;

export enum ReportType {
  PROJECT_STATUS = 'PROJECT_STATUS',

  RISK_REPORT = 'RISK_REPORT',

  ISSUE_REPORT = 'ISSUE_REPORT',

  DELAY_REPORT = 'DELAY_REPORT',

  TEAM_PERFORMANCE = 'TEAM_PERFORMANCE',
}

@Schema({
  timestamps: true,
})
export class Report {
  @Prop({
    type: Types.ObjectId,
    ref: 'Company',
    required: true,
  })
  companyId: Types.ObjectId;

  @Prop({
    required: true,
    enum: ReportType,
    // index: true,
  })
  reportType: ReportType;

  /**
   * Optional Project
   */
  @Prop({
    type: Types.ObjectId,
    ref: 'Project',
    // index: true,
  })
  projectId?: Types.ObjectId;

  /**
   * Generated By User
   */
  @Prop({
    type: Types.ObjectId,
    ref: 'User',
    required: true,
    // index: true,
  })
  generatedBy: Types.ObjectId;

  /**
   * Report Title
   */
  @Prop({
    trim: true,
    maxlength: 250,
  })
  title: string;

  @Prop({
    trim: true,
    maxlength: 3000,
  })
  description: string;

  /**
   * AI Generated Report
   */
  @Prop({
    type: MongooseSchema.Types.Mixed,
    required: true,
  })
  content: Record<string, any>;

  @Prop()
  regeneratedAt?: Date;

  /**
   * Optional JSON Data
   * Used for charts/statistics
   */
  @Prop({
    type: Object,
  })
  metadata?: Record<string, any>;

  /**
   * Soft Delete
   */
  @Prop({
    default: false,
    //index: true,
  })
  isDeleted: boolean;
}

export const ReportSchema = SchemaFactory.createForClass(Report);

ReportSchema.index({
  reportType: 1,
});

ReportSchema.index({
  generatedBy: 1,
});

ReportSchema.index({
  projectId: 1,
});

ReportSchema.index({
  companyId: 1,
});

ReportSchema.index({
  createdAt: -1,
});

ReportSchema.index({
  isDeleted: 1,
});

ReportSchema.index({
  reportType: 1,
  createdAt: -1,
});

ReportSchema.index({
  generatedBy: 1,
  createdAt: -1,
});

ReportSchema.index({
  projectId: 1,
  reportType: 1,
});
